# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age177zxradnnt0ahfn0435wlsw5s0j7lp283954pvyw9ycawrx6kqts73twht
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1ZDFZTWFtaUhhY2VoM2lZ
        Y01MQlZJWXd1Y1BxRkhPcEpIL2IxS3JiMldrCk9Yd3hLM2djNWRjMlVTQmhQZmd0
        ZUlaeGVxRjVrcXNuU0xheGxXaDM0Q28KLS0tIHhmWUQrdmVNYWJNWStWS2pSckdS
        c0VlUlZxbnoxZ1k1RFo2VlJvYVh0RGMKH4G2XkXP4q+qRs4dkbtRnG26hdGvKwWx
        UC/Ft3jFl377Y2lFK8TAMby+hA3xVg8vgil36sxONx9JaOnlsd6o5w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T16:26:46Z"
  mac: ENC[AES256_GCM,data:e02gL4/lV6ssBkyiKUMFq9USxavd5hrvkdEXH3kU4XXGkko/+/N1t8ophNNYsxJviSV1QK2IFaZYMRwG0k77VRy4YEVe5EDq58vXJfv6BM1LbBfN6+XGQUxKKoaierLdUFCa3B8IWgjEK01W5Jsq4lazUieWnzojDzMKdz/bDRo=,iv:f2E78hJeEMlUC18rxqAQ6b+kwqPZlzNRULYWB9BWLoM=,tag:g2T7swlOm5BeKxuewmI0Zg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
