# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ""
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age177zxradnnt0ahfn0435wlsw5s0j7lp283954pvyw9ycawrx6kqts73twht
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxb200S1VHWmtUQmx0Mm5s
        L1FPeHpOYlpSYWZXS3MxRmNOQ0tTVzlJNHowCkJmeWp2VDJySFltbVVzZGVmZ0pN
        UTVMQlRZL3FtQXRrS0JsUFJDT0lCQnMKLS0tIDZ0NEZNVnJ3TU96dndRQmNLWXU5
        c2VMYllka3B5eHF1aGpVUTR4MG1tdGcKK/4cYHaWhlz/0yy3GSqMeut2LQgC6uVr
        HgWRkjoryg+0tZZY3UwwcKSlqs2bWyN0toMjV4STHE+nhpFRwxHW+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T18:25:05Z"
  mac: ENC[AES256_GCM,data:InbrYzqcPl2uEHy/uSdtq3KO78+g8i3TWMFpQzC5QtwX4RgpQ7qVWkS2HKtaDQKWBYSMfXia/bFyhmofBvfGFwtKSsmWYnIdccQuncFbYtVUAZvR2YWWDC+vPPGdVXrB0snxfPV8oDJTvDcTqE0XauSrQqaoKIe9i8/Taths+A4=,iv:McBaq3o2PQoyKfn47Mr+AXgQ9ZpnzRMJsGQwQxli6FY=,tag:RjEe3LPC/wtlD/9FdioH9A==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
