# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:d37WFmUDfQB3bTFL4v+Ad5UdxTcLaSjDGoj7bLwW0sirWwqOeSXyGQ==,iv:TXN3IMMpK2WbrlQZuKyyF7Isrmpg3tfWsa+nBx6dEH0=,tag:bKnxlWekdeRoDqnY1hNWow==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age177zxradnnt0ahfn0435wlsw5s0j7lp283954pvyw9ycawrx6kqts73twht
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTTFjWkxUWXVHdm5iOTJm
        aW82MHRRMTlTTDhhcmhveGFzSWFXU3lsNmwwCkMyRTBGeGRXaGFSSStYRk8yUXBw
        bmhhWkRibW1ZNk9OM2JZR3RzVi85Y1UKLS0tIFpla3p3N1RPenJpQ3ZWRmlYVlNa
        ajMxeXpUNDJMYUE4aWtSRHpsMkZwS28KX5D9dpCntlqr2EwdrDOIyugs+t7Q3nwG
        4x38w341/c0YkpT7Fbhfbvex9wcfd1wV5r+sX/463rkOiOAVnPWFiQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-02-06T16:26:46Z"
  mac: ENC[AES256_GCM,data:5yP+mzod19AVTf8euMrdesaH2dwul5O8R2tldgPyIrCbvhdhRNLvpx7zRqoGbJAYuwJWFSSgteka5X4dGkpw9jUhV8KdvBsyj5IQXg3GGCo+0uiqv8GybB6bcyznHD3td7sL6GVtUo3t0UcbuoO7pn9sHPVwRfxSFIsj3iMv3e4=,iv:um/0bSCSGHri/ZoCgTMaKtaB5Nl6WaBeL1x+8NkjVEw=,tag:HAycPN6PqUZTWSU9kINUdA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
